config/routes.rb
Rails.application.routes.draw do
  resources :phones
  root 'phones#index'

end

app/models/phone.rb
class Phone < ActiveRecord::Base
	has_many :phone_images, :dependent => :destroy

	def as_json(options = {})
		if options[:mode] == 'list'
			super({only: [:id, :name, :age, :display], include: { phone_images: {only: :url}} } )
		else
			super(include: {phone_images: {only: :url}})
		end
	end
end

app/models/phone_image.rb
class PhoneImage < ActiveRecord::Base
	belongs_to :phone

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
    respond_to do |format|
      format.html
      format.json { render :json => @phones.as_json(mode:'list') }
    end
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @phone = Phone.find params[:id]
    respond_to do |format|
      format.html
      format.json { render :json => @phone.as_json }
    end
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params[:phone]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="phonecatApp">
<head>
  <title>AngularApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-controller="PhoneListCtrl">

<%= yield %>

</body>
</html>

app/views/phones/_form.html.slim
= form_for @phone do |f|
  - if @phone.errors.any?
    #error_explanation
      h2 = "#{pluralize(@phone.errors.count, "error")} prohibited this phone from being saved:"
      ul
        - @phone.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/phones/edit.html.slim
h1 Editing phone

== render 'form'

= link_to 'Show', @phone
'|
= link_to 'Back', phones_path

app/views/phones/index.html.slim
.view-container
	.view-frame ng-view=""

app/views/phones/new.html.slim
h1 New phone

== render 'form'

= link_to 'Back', phones_path

app/views/phones/show.html.slim
p#notice = notice


= link_to 'Edit', edit_phone_path(@phone)
'|
= link_to 'Back', phones_path